version: '3.4'

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - TIMESTAMP=$(date +%s)
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=secureaccess
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=userprime
      - MYSQL_PASSWORD=secureaccess
      
      - DB_HOST=mysql
      - DB_USERNAME=userprime
      - DB_PASSWORD=secureaccess
      - DB_DATABASE=mydatabase
    networks:
      - internalnet


  api:
    build: ./api
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
    environment:
      PORT: 3000
      HOSTNAME: api
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DATABASE: challenge3
    container_name: node-service
    networks:
      - internalnet

  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    expose:
      - 8080
    depends_on:
      - api
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge