version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=mariadb
        DB_USERNAME=userprime
        DB_PASSWORD=secureaccess
        DB_DATABASE=mydatabase
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  db_data:

networks:
  default:
    external:
      true